// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"
#include "screens/ui_Screen5.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_673166940);    // assets/首页.png
LV_IMG_DECLARE(ui_img_1663005091);    // assets/灯光.png
LV_IMG_DECLARE(ui_img_399794486);    // assets/通风风扇.png
LV_IMG_DECLARE(ui_img_1887403499);    // assets/设置.png
LV_IMG_DECLARE(ui_img_237420965);    // assets/数据.png
LV_IMG_DECLARE(ui_img_84551563);    // assets/灯光总开关.png
LV_IMG_DECLARE(ui_img_688870236);    // assets/i-窗帘.png
LV_IMG_DECLARE(ui_img_181976582);    // assets/空调.png
LV_IMG_DECLARE(ui_img_994938910);    // assets/卧室.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font22);
LV_FONT_DECLARE(ui_font_Font25);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
