// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Container10;
extern void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern void ui_event_Image15(lv_event_t * e);
extern lv_obj_t * ui_Image15;
extern void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern void ui_event_Image16(lv_event_t * e);
extern lv_obj_t * ui_Image16;
extern void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern void ui_event_Image17(lv_event_t * e);
extern lv_obj_t * ui_Image17;
extern void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern void ui_event_Image18(lv_event_t * e);
extern lv_obj_t * ui_Image18;
extern void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern void ui_event_Image19(lv_event_t * e);
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Button37;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Button30;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Button34;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Button35;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_Button41;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Button36;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Button38;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Button39;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_Switch6;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_Switch8;
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_RPMlable;
extern lv_obj_t * ui_Label62;
extern lv_obj_t * ui_Slider6;
extern lv_obj_t * ui_Label63;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

