// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern void ui_event_Image3(lv_event_t * e);
extern lv_obj_t * ui_Image3;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern void ui_event_Image4(lv_event_t * e);
extern lv_obj_t * ui_Image4;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern void ui_event_Image5(lv_event_t * e);
extern lv_obj_t * ui_Image5;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern void ui_event_Image6(lv_event_t * e);
extern lv_obj_t * ui_Image6;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Container2;
extern void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container4;
extern void ui_event_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Slider3;
extern void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Container5;
extern void ui_event_Slider4(lv_event_t * e);
extern lv_obj_t * ui_Slider4;
extern void ui_event_Switch4(lv_event_t * e);
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Container6;
extern void ui_event_Slider5(lv_event_t * e);
extern lv_obj_t * ui_Slider5;
extern void ui_event_Switch5(lv_event_t * e);
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

