// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Container9;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern void ui_event_Image11(lv_event_t * e);
extern lv_obj_t * ui_Image11;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern void ui_event_Image12(lv_event_t * e);
extern lv_obj_t * ui_Image12;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern void ui_event_Image13(lv_event_t * e);
extern lv_obj_t * ui_Image13;
extern void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern void ui_event_Image14(lv_event_t * e);
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label30;
extern void ui_event_Button26(lv_event_t * e);
extern lv_obj_t * ui_Button26;
extern lv_obj_t * ui_Image30;
extern void ui_event_Button28(lv_event_t * e);
extern lv_obj_t * ui_Button28;
extern lv_obj_t * ui_Image32;
extern void ui_event_Button29(lv_event_t * e);
extern lv_obj_t * ui_Button29;
extern lv_obj_t * ui_Image33;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Button27;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Button31;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Button32;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Button33;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Slider7;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label47;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

