// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_Button16 = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_Button17 = NULL;
lv_obj_t * ui_Image21 = NULL;
lv_obj_t * ui_Button18 = NULL;
lv_obj_t * ui_Image22 = NULL;
lv_obj_t * ui_Button19 = NULL;
lv_obj_t * ui_Image23 = NULL;
lv_obj_t * ui_Button20 = NULL;
lv_obj_t * ui_Image24 = NULL;
lv_obj_t * ui_Container21 = NULL;
lv_obj_t * ui_Label65 = NULL;
lv_obj_t * ui_Label61 = NULL;
lv_obj_t * ui_Container22 = NULL;
lv_obj_t * ui_Label67 = NULL;
lv_obj_t * ui_Label64 = NULL;
lv_obj_t * ui_Container23 = NULL;
lv_obj_t * ui_Label68 = NULL;
lv_obj_t * ui_Label69 = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_TabView3 = NULL;
lv_obj_t * ui_TabPage1 = NULL;
// event funtions
void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Image20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Image21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Image22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Image23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_Image24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen4_screen_init);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label28, 100);
    lv_obj_set_height(ui_Label28, 40);
    lv_obj_set_x(ui_Label28, 100);
    lv_obj_set_y(ui_Label28, 30);
    lv_label_set_text(ui_Label28, "数据监控");
    lv_obj_set_style_text_font(ui_Label28, &ui_font_Font25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 80);
    lv_obj_set_height(ui_Container11, 500);
    lv_obj_set_x(ui_Container11, 0);
    lv_obj_set_y(ui_Container11, 30);
    lv_obj_remove_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button16 = lv_button_create(ui_Container11);
    lv_obj_set_width(ui_Button16, 80);
    lv_obj_set_height(ui_Button16, 100);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image20 = lv_image_create(ui_Button16);
    lv_image_set_src(ui_Image20, &ui_img_673166940);
    lv_obj_set_width(ui_Image20, 80);
    lv_obj_set_height(ui_Image20, 100);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image20, 80);

    ui_Button17 = lv_button_create(ui_Container11);
    lv_obj_set_width(ui_Button17, 80);
    lv_obj_set_height(ui_Button17, 100);
    lv_obj_set_x(ui_Button17, 0);
    lv_obj_set_y(ui_Button17, 100);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image21 = lv_image_create(ui_Button17);
    lv_image_set_src(ui_Image21, &ui_img_1663005091);
    lv_obj_set_width(ui_Image21, 80);
    lv_obj_set_height(ui_Image21, 100);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image21, 80);

    ui_Button18 = lv_button_create(ui_Container11);
    lv_obj_set_width(ui_Button18, 80);
    lv_obj_set_height(ui_Button18, 100);
    lv_obj_set_x(ui_Button18, 0);
    lv_obj_set_y(ui_Button18, 200);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image22 = lv_image_create(ui_Button18);
    lv_image_set_src(ui_Image22, &ui_img_399794486);
    lv_obj_set_width(ui_Image22, 80);
    lv_obj_set_height(ui_Image22, 100);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image22, 80);

    ui_Button19 = lv_button_create(ui_Container11);
    lv_obj_set_width(ui_Button19, 80);
    lv_obj_set_height(ui_Button19, 100);
    lv_obj_set_x(ui_Button19, 0);
    lv_obj_set_y(ui_Button19, 400);
    lv_obj_add_flag(ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image23 = lv_image_create(ui_Button19);
    lv_image_set_src(ui_Image23, &ui_img_1887403499);
    lv_obj_set_width(ui_Image23, 80);
    lv_obj_set_height(ui_Image23, 100);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image23, 80);

    ui_Button20 = lv_button_create(ui_Container11);
    lv_obj_set_width(ui_Button20, 80);
    lv_obj_set_height(ui_Button20, 100);
    lv_obj_set_x(ui_Button20, 0);
    lv_obj_set_y(ui_Button20, 300);
    lv_obj_add_flag(ui_Button20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button20, lv_color_hex(0xBCD1D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image24 = lv_image_create(ui_Button20);
    lv_image_set_src(ui_Image24, &ui_img_237420965);
    lv_obj_set_width(ui_Image24, 80);
    lv_obj_set_height(ui_Image24, 100);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image24, 80);

    ui_Container21 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container21);
    lv_obj_set_width(ui_Container21, 270);
    lv_obj_set_height(ui_Container21, 150);
    lv_obj_set_x(ui_Container21, 100);
    lv_obj_set_y(ui_Container21, 70);
    lv_obj_remove_flag(ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Container21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Container21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label65 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label65, 240);
    lv_obj_set_y(ui_Label65, 7);
    lv_label_set_text(ui_Label65, "°C");

    ui_Label61 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, 0);
    lv_obj_set_y(ui_Label61, 9);
    lv_label_set_text(ui_Label61, "温度");
    lv_obj_set_style_text_font(ui_Label61, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container22 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container22);
    lv_obj_set_width(ui_Container22, 270);
    lv_obj_set_height(ui_Container22, 150);
    lv_obj_set_x(ui_Container22, 400);
    lv_obj_set_y(ui_Container22, 70);
    lv_obj_remove_flag(ui_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Container22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Container22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label67 = lv_label_create(ui_Container22);
    lv_obj_set_width(ui_Label67, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label67, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label67, 240);
    lv_obj_set_y(ui_Label67, 7);
    lv_label_set_text(ui_Label67, "°C");

    ui_Label64 = lv_label_create(ui_Container22);
    lv_obj_set_width(ui_Label64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label64, 0);
    lv_obj_set_y(ui_Label64, 9);
    lv_label_set_text(ui_Label64, "温度");
    lv_obj_set_style_text_font(ui_Label64, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container23 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container23);
    lv_obj_set_width(ui_Container23, 270);
    lv_obj_set_height(ui_Container23, 150);
    lv_obj_set_x(ui_Container23, 700);
    lv_obj_set_y(ui_Container23, 70);
    lv_obj_remove_flag(ui_Container23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Container23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Container23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label68 = lv_label_create(ui_Container23);
    lv_obj_set_width(ui_Label68, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label68, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label68, 240);
    lv_obj_set_y(ui_Label68, 7);
    lv_label_set_text(ui_Label68, "°C");

    ui_Label69 = lv_label_create(ui_Container23);
    lv_obj_set_width(ui_Label69, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label69, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label69, 0);
    lv_obj_set_y(ui_Label69, 9);
    lv_label_set_text(ui_Label69, "温度");
    lv_obj_set_style_text_font(ui_Label69, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Screen4);
    lv_tabview_set_tab_bar_size(ui_TabView1, 50);
    lv_obj_set_width(ui_TabView1, 430);
    lv_obj_set_height(ui_TabView1, 300);
    lv_obj_set_x(ui_TabView1, 100);
    lv_obj_set_y(ui_TabView1, 240);
    lv_obj_remove_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_TabView1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TabView1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_tabview_get_tab_bar(ui_TabView1), &ui_font_Font1,  LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "历史数据");

    ui_TabView3 = lv_tabview_create(ui_Screen4);
    lv_tabview_set_tab_bar_size(ui_TabView3, 50);
    lv_obj_set_width(ui_TabView3, 410);
    lv_obj_set_height(ui_TabView3, 300);
    lv_obj_set_x(ui_TabView3, 560);
    lv_obj_set_y(ui_TabView3, 240);
    lv_obj_remove_flag(ui_TabView3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TabView3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView3, "告警记录");

    lv_obj_add_event_cb(ui_Image20, ui_event_Image20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image21, ui_event_Image21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image22, ui_event_Image22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image23, ui_event_Image23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button19, ui_event_Button19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image24, ui_event_Image24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button20, ui_event_Button20, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Label28 = NULL;
    ui_Container11 = NULL;
    ui_Button16 = NULL;
    ui_Image20 = NULL;
    ui_Button17 = NULL;
    ui_Image21 = NULL;
    ui_Button18 = NULL;
    ui_Image22 = NULL;
    ui_Button19 = NULL;
    ui_Image23 = NULL;
    ui_Button20 = NULL;
    ui_Image24 = NULL;
    ui_Container21 = NULL;
    ui_Label65 = NULL;
    ui_Label61 = NULL;
    ui_Container22 = NULL;
    ui_Label67 = NULL;
    ui_Label64 = NULL;
    ui_Container23 = NULL;
    ui_Label68 = NULL;
    ui_Label69 = NULL;
    ui_TabView1 = NULL;
    ui_TabPage2 = NULL;
    ui_TabView3 = NULL;
    ui_TabPage1 = NULL;

}
