// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Button9 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Button10 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_Button26 = NULL;
lv_obj_t * ui_Image30 = NULL;
lv_obj_t * ui_Button28 = NULL;
lv_obj_t * ui_Image32 = NULL;
lv_obj_t * ui_Button29 = NULL;
lv_obj_t * ui_Image33 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_Button27 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_Button31 = NULL;
lv_obj_t * ui_Label42 = NULL;
lv_obj_t * ui_Button32 = NULL;
lv_obj_t * ui_Label43 = NULL;
lv_obj_t * ui_Button33 = NULL;
lv_obj_t * ui_Label44 = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_Label36 = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_Slider7 = NULL;
lv_obj_t * ui_Container15 = NULL;
lv_obj_t * ui_Label40 = NULL;
lv_obj_t * ui_Label46 = NULL;
lv_obj_t * ui_Label41 = NULL;
lv_obj_t * ui_Label47 = NULL;
// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Image1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Image11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Image12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Image13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_Image14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_Button26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_Button29, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button28, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Button28(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_Button26, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button29, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Button29(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_Button28, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button26, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label26 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label26, 100);
    lv_obj_set_height(ui_Label26, 40);
    lv_obj_set_x(ui_Label26, 100);
    lv_obj_set_y(ui_Label26, 30);
    lv_label_set_text(ui_Label26, "灯光控制");
    lv_obj_set_style_text_font(ui_Label26, &ui_font_Font25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 80);
    lv_obj_set_height(ui_Container9, 500);
    lv_obj_set_x(ui_Container9, 0);
    lv_obj_set_y(ui_Container9, 30);
    lv_obj_remove_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_button_create(ui_Container9);
    lv_obj_set_width(ui_Button2, 80);
    lv_obj_set_height(ui_Button2, 100);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Button2);
    lv_image_set_src(ui_Image1, &ui_img_673166940);
    lv_obj_set_width(ui_Image1, 80);
    lv_obj_set_height(ui_Image1, 100);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image1, 80);

    ui_Button7 = lv_button_create(ui_Container9);
    lv_obj_set_width(ui_Button7, 80);
    lv_obj_set_height(ui_Button7, 100);
    lv_obj_set_x(ui_Button7, 0);
    lv_obj_set_y(ui_Button7, 100);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xBCD1D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_image_create(ui_Button7);
    lv_image_set_src(ui_Image11, &ui_img_1663005091);
    lv_obj_set_width(ui_Image11, 80);
    lv_obj_set_height(ui_Image11, 100);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image11, 80);

    ui_Button8 = lv_button_create(ui_Container9);
    lv_obj_set_width(ui_Button8, 80);
    lv_obj_set_height(ui_Button8, 100);
    lv_obj_set_x(ui_Button8, 0);
    lv_obj_set_y(ui_Button8, 200);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_image_create(ui_Button8);
    lv_image_set_src(ui_Image12, &ui_img_399794486);
    lv_obj_set_width(ui_Image12, 80);
    lv_obj_set_height(ui_Image12, 100);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image12, 80);

    ui_Button9 = lv_button_create(ui_Container9);
    lv_obj_set_width(ui_Button9, 80);
    lv_obj_set_height(ui_Button9, 100);
    lv_obj_set_x(ui_Button9, 0);
    lv_obj_set_y(ui_Button9, 400);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_image_create(ui_Button9);
    lv_image_set_src(ui_Image13, &ui_img_1887403499);
    lv_obj_set_width(ui_Image13, 80);
    lv_obj_set_height(ui_Image13, 100);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image13, 80);

    ui_Button10 = lv_button_create(ui_Container9);
    lv_obj_set_width(ui_Button10, 80);
    lv_obj_set_height(ui_Button10, 100);
    lv_obj_set_x(ui_Button10, 0);
    lv_obj_set_y(ui_Button10, 300);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image14 = lv_image_create(ui_Button10);
    lv_image_set_src(ui_Image14, &ui_img_237420965);
    lv_obj_set_width(ui_Image14, 80);
    lv_obj_set_height(ui_Image14, 100);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image14, 80);

    ui_Container8 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 400);
    lv_obj_set_height(ui_Container8, 300);
    lv_obj_set_x(ui_Container8, 100);
    lv_obj_set_y(ui_Container8, 80);
    lv_obj_remove_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 20);
    lv_obj_set_y(ui_Label30, 6);
    lv_label_set_text(ui_Label30, "灯光列表");
    lv_obj_set_style_text_font(ui_Label30, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button26 = lv_button_create(ui_Container8);
    lv_obj_set_width(ui_Button26, 380);
    lv_obj_set_height(ui_Button26, 70);
    lv_obj_set_x(ui_Button26, 20);
    lv_obj_set_y(ui_Button26, 40);
    lv_obj_add_flag(ui_Button26, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button26, lv_color_hex(0xB7C472), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button26, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image30 = lv_image_create(ui_Button26);
    lv_image_set_src(ui_Image30, &ui_img_84551563);
    lv_obj_set_width(ui_Image30, 50);
    lv_obj_set_height(ui_Image30, 50);
    lv_obj_set_x(ui_Image30, 0);
    lv_obj_set_y(ui_Image30, -10);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image30, 50);

    ui_Button28 = lv_button_create(ui_Container8);
    lv_obj_set_width(ui_Button28, 380);
    lv_obj_set_height(ui_Button28, 70);
    lv_obj_set_x(ui_Button28, 20);
    lv_obj_set_y(ui_Button28, 130);
    lv_obj_add_flag(ui_Button28, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button28, lv_color_hex(0xB7C472), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button28, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image32 = lv_image_create(ui_Button28);
    lv_image_set_src(ui_Image32, &ui_img_994938910);
    lv_obj_set_width(ui_Image32, 50);
    lv_obj_set_height(ui_Image32, 50);
    lv_obj_set_x(ui_Image32, 0);
    lv_obj_set_y(ui_Image32, -10);
    lv_obj_add_flag(ui_Image32, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image32, 50);

    ui_Button29 = lv_button_create(ui_Container8);
    lv_obj_set_width(ui_Button29, 380);
    lv_obj_set_height(ui_Button29, 70);
    lv_obj_set_x(ui_Button29, 20);
    lv_obj_set_y(ui_Button29, 220);
    lv_obj_add_flag(ui_Button29, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button29, lv_color_hex(0xB7C472), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button29, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image33 = lv_image_create(ui_Button29);
    lv_image_set_src(ui_Image33, &ui_img_84551563);
    lv_obj_set_width(ui_Image33, 50);
    lv_obj_set_height(ui_Image33, 50);
    lv_obj_set_x(ui_Image33, 0);
    lv_obj_set_y(ui_Image33, -10);
    lv_obj_add_flag(ui_Image33, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image33, 50);

    ui_Label32 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -240);
    lv_obj_set_y(ui_Label32, -155);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "客厅主灯");
    lv_obj_set_style_text_font(ui_Label32, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, -240);
    lv_obj_set_y(ui_Label31, -65);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "卧室灯");
    lv_obj_set_style_text_font(ui_Label31, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -238);
    lv_obj_set_y(ui_Label33, 25);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "餐厅灯");
    lv_obj_set_style_text_font(ui_Label33, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 400);
    lv_obj_set_height(ui_Container13, 100);
    lv_obj_set_x(ui_Container13, 100);
    lv_obj_set_y(ui_Container13, 390);
    lv_obj_remove_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label35, "场景模式");
    lv_obj_set_style_text_font(ui_Label35, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button27 = lv_button_create(ui_Container13);
    lv_obj_set_width(ui_Button27, 60);
    lv_obj_set_height(ui_Button27, 30);
    lv_obj_set_x(ui_Button27, 20);
    lv_obj_set_y(ui_Button27, 40);
    lv_obj_add_flag(ui_Button27, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button27, lv_color_hex(0xA5C6D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Button27);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "明亮");
    lv_obj_set_style_text_font(ui_Label39, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button31 = lv_button_create(ui_Container13);
    lv_obj_set_width(ui_Button31, 60);
    lv_obj_set_height(ui_Button31, 30);
    lv_obj_set_x(ui_Button31, 100);
    lv_obj_set_y(ui_Button31, 40);
    lv_obj_add_flag(ui_Button31, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button31, lv_color_hex(0xA5C6D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_Button31);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "阅读");
    lv_obj_set_style_text_font(ui_Label42, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button32 = lv_button_create(ui_Container13);
    lv_obj_set_width(ui_Button32, 60);
    lv_obj_set_height(ui_Button32, 30);
    lv_obj_set_x(ui_Button32, 180);
    lv_obj_set_y(ui_Button32, 40);
    lv_obj_add_flag(ui_Button32, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button32, lv_color_hex(0xA5C6D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_Button32);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "观影");
    lv_obj_set_style_text_font(ui_Label43, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button33 = lv_button_create(ui_Container13);
    lv_obj_set_width(ui_Button33, 60);
    lv_obj_set_height(ui_Button33, 30);
    lv_obj_set_x(ui_Button33, 260);
    lv_obj_set_y(ui_Button33, 40);
    lv_obj_add_flag(ui_Button33, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button33, lv_color_hex(0xA5C6D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_Button33);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "睡眠");
    lv_obj_set_style_text_font(ui_Label44, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 450);
    lv_obj_set_height(ui_Container14, 300);
    lv_obj_set_x(ui_Container14, 550);
    lv_obj_set_y(ui_Container14, 80);
    lv_obj_remove_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 20);
    lv_obj_set_y(ui_Label22, 6);
    lv_label_set_text(ui_Label22, "当前灯具:");
    lv_obj_set_style_text_font(ui_Label22, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, 20);
    lv_obj_set_y(ui_Label34, 50);
    lv_label_set_text(ui_Label34, "电源开关");
    lv_obj_set_style_text_font(ui_Label34, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Container14);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 350);
    lv_obj_set_y(ui_Switch2, 50);

    ui_Slider2 = lv_slider_create(ui_Container14);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 150);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, 250);
    lv_obj_set_y(ui_Slider2, 100);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider2,
                                                                                              lv_obj_get_style_pad_right(ui_Slider2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label36 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 20);
    lv_obj_set_y(ui_Label36, 100);
    lv_label_set_text(ui_Label36, "亮度");
    lv_obj_set_style_text_font(ui_Label36, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 20);
    lv_obj_set_y(ui_Label37, 150);
    lv_label_set_text(ui_Label37, "色温");
    lv_obj_set_style_text_font(ui_Label37, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, 20);
    lv_obj_set_y(ui_Label38, 200);
    lv_label_set_text(ui_Label38, "设备");
    lv_obj_set_style_text_font(ui_Label38, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider7 = lv_slider_create(ui_Container14);
    lv_slider_set_value(ui_Slider7, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider7) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_Slider7, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider7, 150);
    lv_obj_set_height(ui_Slider7, 10);
    lv_obj_set_x(ui_Slider7, 250);
    lv_obj_set_y(ui_Slider7, 150);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider7, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider7,
                                                                                              lv_obj_get_style_pad_right(ui_Slider7, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Container15 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 450);
    lv_obj_set_height(ui_Container15, 150);
    lv_obj_set_x(ui_Container15, 550);
    lv_obj_set_y(ui_Container15, 390);
    lv_obj_remove_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, 20);
    lv_obj_set_y(ui_Label40, 6);
    lv_label_set_text(ui_Label40, "当前亮度映射");
    lv_obj_set_style_text_font(ui_Label40, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label46 = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, 20);
    lv_obj_set_y(ui_Label46, 50);
    lv_label_set_text(ui_Label46, "PWM占空比");
    lv_obj_set_style_text_font(ui_Label46, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 20);
    lv_obj_set_y(ui_Label41, 90);
    lv_label_set_text(ui_Label41, "驱动接口");
    lv_obj_set_style_text_font(ui_Label41, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, 20);
    lv_obj_set_y(ui_Label47, 130);
    lv_label_set_text(ui_Label47, "校验结果");
    lv_obj_set_style_text_font(ui_Label47, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image1, ui_event_Image1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image11, ui_event_Image11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image12, ui_event_Image12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image13, ui_event_Image13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image14, ui_event_Image14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button26, ui_event_Button26, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button28, ui_event_Button28, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button29, ui_event_Button29, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Label26 = NULL;
    ui_Container9 = NULL;
    ui_Button2 = NULL;
    ui_Image1 = NULL;
    ui_Button7 = NULL;
    ui_Image11 = NULL;
    ui_Button8 = NULL;
    ui_Image12 = NULL;
    ui_Button9 = NULL;
    ui_Image13 = NULL;
    ui_Button10 = NULL;
    ui_Image14 = NULL;
    ui_Container8 = NULL;
    ui_Label30 = NULL;
    ui_Button26 = NULL;
    ui_Image30 = NULL;
    ui_Button28 = NULL;
    ui_Image32 = NULL;
    ui_Button29 = NULL;
    ui_Image33 = NULL;
    ui_Label32 = NULL;
    ui_Label31 = NULL;
    ui_Label33 = NULL;
    ui_Container13 = NULL;
    ui_Label35 = NULL;
    ui_Button27 = NULL;
    ui_Label39 = NULL;
    ui_Button31 = NULL;
    ui_Label42 = NULL;
    ui_Button32 = NULL;
    ui_Label43 = NULL;
    ui_Button33 = NULL;
    ui_Label44 = NULL;
    ui_Container14 = NULL;
    ui_Label22 = NULL;
    ui_Label34 = NULL;
    ui_Switch2 = NULL;
    ui_Slider2 = NULL;
    ui_Label36 = NULL;
    ui_Label37 = NULL;
    ui_Label38 = NULL;
    ui_Slider7 = NULL;
    ui_Container15 = NULL;
    ui_Label40 = NULL;
    ui_Label46 = NULL;
    ui_Label41 = NULL;
    ui_Label47 = NULL;

}
