// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Container12 = NULL;
lv_obj_t * ui_Button21 = NULL;
lv_obj_t * ui_Image25 = NULL;
lv_obj_t * ui_Button22 = NULL;
lv_obj_t * ui_Image26 = NULL;
lv_obj_t * ui_Button23 = NULL;
lv_obj_t * ui_Image27 = NULL;
lv_obj_t * ui_Button24 = NULL;
lv_obj_t * ui_Image28 = NULL;
lv_obj_t * ui_Button25 = NULL;
lv_obj_t * ui_Image29 = NULL;
// event funtions
void ui_event_Button21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Image25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Image26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Button23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Image27(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Button24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Image28(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Button25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_Image29(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen4_screen_init);
    }
}

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label29 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label29, 100);
    lv_obj_set_height(ui_Label29, 40);
    lv_obj_set_x(ui_Label29, 100);
    lv_obj_set_y(ui_Label29, 30);
    lv_label_set_text(ui_Label29, "网关设置");
    /* 标题用 Font1（含完整中文子集 269 字符），避免 SquareLine Font25 子集不全显示方块 */
    lv_obj_set_style_text_font(ui_Label29, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container12 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 80);
    lv_obj_set_height(ui_Container12, 500);
    lv_obj_set_x(ui_Container12, 0);
    lv_obj_set_y(ui_Container12, 30);
    lv_obj_remove_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button21 = lv_button_create(ui_Container12);
    lv_obj_set_width(ui_Button21, 80);
    lv_obj_set_height(ui_Button21, 100);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image25 = lv_image_create(ui_Button21);
    lv_image_set_src(ui_Image25, &ui_img_673166940);
    lv_obj_set_width(ui_Image25, 80);
    lv_obj_set_height(ui_Image25, 100);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image25, 80);

    ui_Button22 = lv_button_create(ui_Container12);
    lv_obj_set_width(ui_Button22, 80);
    lv_obj_set_height(ui_Button22, 100);
    lv_obj_set_x(ui_Button22, 0);
    lv_obj_set_y(ui_Button22, 100);
    lv_obj_add_flag(ui_Button22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image26 = lv_image_create(ui_Button22);
    lv_image_set_src(ui_Image26, &ui_img_1663005091);
    lv_obj_set_width(ui_Image26, 80);
    lv_obj_set_height(ui_Image26, 100);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image26, 80);

    ui_Button23 = lv_button_create(ui_Container12);
    lv_obj_set_width(ui_Button23, 80);
    lv_obj_set_height(ui_Button23, 100);
    lv_obj_set_x(ui_Button23, 0);
    lv_obj_set_y(ui_Button23, 200);
    lv_obj_add_flag(ui_Button23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image27 = lv_image_create(ui_Button23);
    lv_image_set_src(ui_Image27, &ui_img_399794486);
    lv_obj_set_width(ui_Image27, 80);
    lv_obj_set_height(ui_Image27, 100);
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image27, 80);

    ui_Button24 = lv_button_create(ui_Container12);
    lv_obj_set_width(ui_Button24, 80);
    lv_obj_set_height(ui_Button24, 100);
    lv_obj_set_x(ui_Button24, 0);
    lv_obj_set_y(ui_Button24, 400);
    lv_obj_add_flag(ui_Button24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button24, lv_color_hex(0xBCD1D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image28 = lv_image_create(ui_Button24);
    lv_image_set_src(ui_Image28, &ui_img_1887403499);
    lv_obj_set_width(ui_Image28, 80);
    lv_obj_set_height(ui_Image28, 100);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image28, 80);

    ui_Button25 = lv_button_create(ui_Container12);
    lv_obj_set_width(ui_Button25, 80);
    lv_obj_set_height(ui_Button25, 100);
    lv_obj_set_x(ui_Button25, 0);
    lv_obj_set_y(ui_Button25, 300);
    lv_obj_add_flag(ui_Button25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image29 = lv_image_create(ui_Button25);
    lv_image_set_src(ui_Image29, &ui_img_237420965);
    lv_obj_set_width(ui_Image29, 80);
    lv_obj_set_height(ui_Image29, 100);
    lv_obj_set_align(ui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image29, 80);

    lv_obj_add_event_cb(ui_Image25, ui_event_Image25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button21, ui_event_Button21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image26, ui_event_Image26, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button22, ui_event_Button22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image27, ui_event_Image27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button23, ui_event_Button23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image28, ui_event_Image28, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button24, ui_event_Button24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image29, ui_event_Image29, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button25, ui_event_Button25, LV_EVENT_ALL, NULL);

}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_Label29 = NULL;
    ui_Container12 = NULL;
    ui_Button21 = NULL;
    ui_Image25 = NULL;
    ui_Button22 = NULL;
    ui_Image26 = NULL;
    ui_Button23 = NULL;
    ui_Image27 = NULL;
    ui_Button24 = NULL;
    ui_Image28 = NULL;
    ui_Button25 = NULL;
    ui_Image29 = NULL;

}
