// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Container11;
extern void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern void ui_event_Image20(lv_event_t * e);
extern lv_obj_t * ui_Image20;
extern void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern void ui_event_Image21(lv_event_t * e);
extern lv_obj_t * ui_Image21;
extern void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern void ui_event_Image22(lv_event_t * e);
extern lv_obj_t * ui_Image22;
extern void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern void ui_event_Image23(lv_event_t * e);
extern lv_obj_t * ui_Image23;
extern void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern void ui_event_Image24(lv_event_t * e);
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Container21;
extern lv_obj_t * ui_Label65;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_Container22;
extern lv_obj_t * ui_Label67;
extern lv_obj_t * ui_Label64;
extern lv_obj_t * ui_Container23;
extern lv_obj_t * ui_Label68;
extern lv_obj_t * ui_Label69;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_TabView3;
extern lv_obj_t * ui_TabPage1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

