// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Container12;
extern void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
extern void ui_event_Image25(lv_event_t * e);
extern lv_obj_t * ui_Image25;
extern void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern void ui_event_Image26(lv_event_t * e);
extern lv_obj_t * ui_Image26;
extern void ui_event_Button23(lv_event_t * e);
extern lv_obj_t * ui_Button23;
extern void ui_event_Image27(lv_event_t * e);
extern lv_obj_t * ui_Image27;
extern void ui_event_Button24(lv_event_t * e);
extern lv_obj_t * ui_Button24;
extern void ui_event_Image28(lv_event_t * e);
extern lv_obj_t * ui_Image28;
extern void ui_event_Button25(lv_event_t * e);
extern lv_obj_t * ui_Button25;
extern void ui_event_Image29(lv_event_t * e);
extern lv_obj_t * ui_Image29;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

