// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Slider3 = NULL;
lv_obj_t * ui_Switch3 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Slider4 = NULL;
lv_obj_t * ui_Switch4 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Slider5 = NULL;
lv_obj_t * ui_Switch5 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Image3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Image4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Image5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Image6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_Image2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label4, target, "", "%");
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_Label5, target, "开启", "关闭");
    }
}

void ui_event_Slider3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label8, target, "", "%");
    }
}

void ui_event_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_Label7, target, "开启", "关闭");
    }
}

void ui_event_Slider4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label14, target, "", "%");
    }
}

void ui_event_Switch4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_Label13, target, "开启", "关闭");
    }
}

void ui_event_Slider5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label18, target, "", "%");
    }
}

void ui_event_Switch5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_Label17, target, "开启", "关闭");
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 80);
    lv_obj_set_height(ui_Container1, 500);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 30);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_Button1, 80);
    lv_obj_set_height(ui_Button1, 100);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xBCD1D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_Button1);
    lv_image_set_src(ui_Image3, &ui_img_673166940);
    lv_obj_set_width(ui_Image3, 80);
    lv_obj_set_height(ui_Image3, 100);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image3, 80);

    ui_Button3 = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_Button3, 80);
    lv_obj_set_height(ui_Button3, 100);
    lv_obj_set_x(ui_Button3, 0);
    lv_obj_set_y(ui_Button3, 100);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_Button3);
    lv_image_set_src(ui_Image4, &ui_img_1663005091);
    lv_obj_set_width(ui_Image4, 80);
    lv_obj_set_height(ui_Image4, 100);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image4, 80);

    ui_Button4 = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_Button4, 80);
    lv_obj_set_height(ui_Button4, 100);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, 200);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_Button4);
    lv_image_set_src(ui_Image5, &ui_img_399794486);
    lv_obj_set_width(ui_Image5, 80);
    lv_obj_set_height(ui_Image5, 100);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image5, 80);

    ui_Button5 = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_Button5, 80);
    lv_obj_set_height(ui_Button5, 100);
    lv_obj_set_x(ui_Button5, 0);
    lv_obj_set_y(ui_Button5, 400);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_image_create(ui_Button5);
    lv_image_set_src(ui_Image6, &ui_img_1887403499);
    lv_obj_set_width(ui_Image6, 80);
    lv_obj_set_height(ui_Image6, 100);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image6, 80);

    ui_Button6 = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_Button6, 80);
    lv_obj_set_height(ui_Button6, 100);
    lv_obj_set_x(ui_Button6, 0);
    lv_obj_set_y(ui_Button6, 300);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_Button6);
    lv_image_set_src(ui_Image2, &ui_img_237420965);
    lv_obj_set_width(ui_Image2, 80);
    lv_obj_set_height(ui_Image2, 100);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image2, 80);

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 440);
    lv_obj_set_height(ui_Container2, 80);
    lv_obj_set_x(ui_Container2, 100);
    lv_obj_set_y(ui_Container2, 80);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Container2);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 120);
    lv_obj_set_height(ui_Slider1, 3);
    lv_obj_set_x(ui_Slider1, 210);
    lv_obj_set_y(ui_Slider1, 40);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Switch1 = lv_switch_create(ui_Container2);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 380);
    lv_obj_set_y(ui_Switch1, 30);

    ui_Label2 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 80);
    lv_obj_set_y(ui_Label2, 6);
    lv_label_set_text(ui_Label2, "客厅灯光");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 80);
    lv_obj_set_y(ui_Label3, 50);
    lv_label_set_text(ui_Label3, "状态");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 115);
    lv_obj_set_y(ui_Label5, 50);
    lv_label_set_text(ui_Label5, "开启");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x2B1D82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_image_create(ui_Container2);
    lv_image_set_src(ui_Image7, &ui_img_84551563);
    lv_obj_set_width(ui_Image7, 50);
    lv_obj_set_height(ui_Image7, 50);
    lv_obj_set_x(ui_Image7, -189);
    lv_obj_set_y(ui_Image7, -2);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image7, 50);

    ui_Label4 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 129);
    lv_obj_set_y(ui_Label4, 4);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "%0");

    ui_Container4 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 440);
    lv_obj_set_height(ui_Container4, 80);
    lv_obj_set_x(ui_Container4, 100);
    lv_obj_set_y(ui_Container4, 160);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider3 = lv_slider_create(ui_Container4);
    lv_slider_set_value(ui_Slider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 120);
    lv_obj_set_height(ui_Slider3, 3);
    lv_obj_set_x(ui_Slider3, 210);
    lv_obj_set_y(ui_Slider3, 40);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider3, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider3,
                                                                                              lv_obj_get_style_pad_right(ui_Slider3, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Switch3 = lv_switch_create(ui_Container4);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 380);
    lv_obj_set_y(ui_Switch3, 30);

    ui_Label10 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 80);
    lv_obj_set_y(ui_Label10, 6);
    lv_label_set_text(ui_Label10, "风扇");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 80);
    lv_obj_set_y(ui_Label6, 50);
    lv_label_set_text(ui_Label6, "状态");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 115);
    lv_obj_set_y(ui_Label7, 50);
    lv_label_set_text(ui_Label7, "开启");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x2B1D82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_image_create(ui_Container4);
    lv_image_set_src(ui_Image8, &ui_img_399794486);
    lv_obj_set_width(ui_Image8, 50);
    lv_obj_set_height(ui_Image8, 50);
    lv_obj_set_x(ui_Image8, -189);
    lv_obj_set_y(ui_Image8, -2);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image8, 50);

    ui_Label8 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 129);
    lv_obj_set_y(ui_Label8, 4);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "%0");

    ui_Container5 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 440);
    lv_obj_set_height(ui_Container5, 80);
    lv_obj_set_x(ui_Container5, 100);
    lv_obj_set_y(ui_Container5, 240);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider4 = lv_slider_create(ui_Container5);
    lv_slider_set_value(ui_Slider4, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_Slider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider4, 120);
    lv_obj_set_height(ui_Slider4, 3);
    lv_obj_set_x(ui_Slider4, 210);
    lv_obj_set_y(ui_Slider4, 40);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider4, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider4,
                                                                                              lv_obj_get_style_pad_right(ui_Slider4, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Switch4 = lv_switch_create(ui_Container5);
    lv_obj_set_width(ui_Switch4, 50);
    lv_obj_set_height(ui_Switch4, 25);
    lv_obj_set_x(ui_Switch4, 380);
    lv_obj_set_y(ui_Switch4, 30);

    ui_Label11 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 80);
    lv_obj_set_y(ui_Label11, 6);
    lv_label_set_text(ui_Label11, "窗帘");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 80);
    lv_obj_set_y(ui_Label12, 50);
    lv_label_set_text(ui_Label12, "状态");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 115);
    lv_obj_set_y(ui_Label13, 50);
    lv_label_set_text(ui_Label13, "开启");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x2B1D82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_image_create(ui_Container5);
    lv_image_set_src(ui_Image9, &ui_img_688870236);
    lv_obj_set_width(ui_Image9, 50);
    lv_obj_set_height(ui_Image9, 50);
    lv_obj_set_x(ui_Image9, -189);
    lv_obj_set_y(ui_Image9, -2);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image9, 50);

    ui_Label14 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 129);
    lv_obj_set_y(ui_Label14, 4);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "%0");

    ui_Container6 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 440);
    lv_obj_set_height(ui_Container6, 80);
    lv_obj_set_x(ui_Container6, 100);
    lv_obj_set_y(ui_Container6, 320);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider5 = lv_slider_create(ui_Container6);
    lv_slider_set_value(ui_Slider5, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider5) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_Slider5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider5, 120);
    lv_obj_set_height(ui_Slider5, 3);
    lv_obj_set_x(ui_Slider5, 210);
    lv_obj_set_y(ui_Slider5, 40);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider5, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider5,
                                                                                              lv_obj_get_style_pad_right(ui_Slider5, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Switch5 = lv_switch_create(ui_Container6);
    lv_obj_set_width(ui_Switch5, 50);
    lv_obj_set_height(ui_Switch5, 25);
    lv_obj_set_x(ui_Switch5, 380);
    lv_obj_set_y(ui_Switch5, 30);

    ui_Label15 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 80);
    lv_obj_set_y(ui_Label15, 6);
    lv_label_set_text(ui_Label15, "空调");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 80);
    lv_obj_set_y(ui_Label16, 50);
    lv_label_set_text(ui_Label16, "状态");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 115);
    lv_obj_set_y(ui_Label17, 50);
    lv_label_set_text(ui_Label17, "开启");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x2B1D82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_image_create(ui_Container6);
    lv_image_set_src(ui_Image10, &ui_img_181976582);
    lv_obj_set_width(ui_Image10, 50);
    lv_obj_set_height(ui_Image10, 50);
    lv_obj_set_x(ui_Image10, -189);
    lv_obj_set_y(ui_Image10, -2);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image10, 50);

    ui_Label18 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 129);
    lv_obj_set_y(ui_Label18, 4);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "%0");

    ui_Container3 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 450);
    lv_obj_set_height(ui_Container3, 320);
    lv_obj_set_x(ui_Container3, 550);
    lv_obj_set_y(ui_Container3, 80);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Container3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 400);
    lv_obj_set_y(ui_Label19, 30);
    lv_label_set_text(ui_Label19, "°C");

    ui_Label9 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, 30);
    lv_label_set_text(ui_Label9, "温度趋势");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xE51B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 450);
    lv_obj_set_height(ui_Container7, 190);
    lv_obj_set_x(ui_Container7, 550);
    lv_obj_set_y(ui_Container7, 400);
    lv_obj_remove_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 5);
    lv_obj_set_y(ui_Label21, 5);
    lv_label_set_text(ui_Label21, "网关状态");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x1614B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, 40);
    lv_label_set_text(ui_Label20, "在线设备");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 0);
    lv_obj_set_y(ui_Label23, 70);
    lv_label_set_text(ui_Label23, "在线设备");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 0);
    lv_obj_set_y(ui_Label24, 100);
    lv_label_set_text(ui_Label24, "在线设备");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 0);
    lv_obj_set_y(ui_Label25, 130);
    lv_label_set_text(ui_Label25, "在线设备");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, 100);
    lv_obj_set_height(ui_Label1, 40);
    lv_obj_set_x(ui_Label1, 100);
    lv_obj_set_y(ui_Label1, 30);
    lv_label_set_text(ui_Label1, "设备控制");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image4, ui_event_Image4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image5, ui_event_Image5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image6, ui_event_Image6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image2, ui_event_Image2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider3, ui_event_Slider3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch3, ui_event_Switch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider4, ui_event_Slider4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch4, ui_event_Switch4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider5, ui_event_Slider5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch5, ui_event_Switch5, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Container1 = NULL;
    ui_Button1 = NULL;
    ui_Image3 = NULL;
    ui_Button3 = NULL;
    ui_Image4 = NULL;
    ui_Button4 = NULL;
    ui_Image5 = NULL;
    ui_Button5 = NULL;
    ui_Image6 = NULL;
    ui_Button6 = NULL;
    ui_Image2 = NULL;
    ui_Container2 = NULL;
    ui_Slider1 = NULL;
    ui_Switch1 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Label5 = NULL;
    ui_Image7 = NULL;
    ui_Label4 = NULL;
    ui_Container4 = NULL;
    ui_Slider3 = NULL;
    ui_Switch3 = NULL;
    ui_Label10 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_Image8 = NULL;
    ui_Label8 = NULL;
    ui_Container5 = NULL;
    ui_Slider4 = NULL;
    ui_Switch4 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Label13 = NULL;
    ui_Image9 = NULL;
    ui_Label14 = NULL;
    ui_Container6 = NULL;
    ui_Slider5 = NULL;
    ui_Switch5 = NULL;
    ui_Label15 = NULL;
    ui_Label16 = NULL;
    ui_Label17 = NULL;
    ui_Image10 = NULL;
    ui_Label18 = NULL;
    ui_Container3 = NULL;
    ui_Label19 = NULL;
    ui_Label9 = NULL;
    ui_Container7 = NULL;
    ui_Label21 = NULL;
    ui_Label20 = NULL;
    ui_Label23 = NULL;
    ui_Label24 = NULL;
    ui_Label25 = NULL;
    ui_Label1 = NULL;

}
