// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_Button11 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Button12 = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Button13 = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Button14 = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_Button15 = NULL;
lv_obj_t * ui_Image19 = NULL;
lv_obj_t * ui_Container17 = NULL;
lv_obj_t * ui_Label52 = NULL;
lv_obj_t * ui_Button37 = NULL;
lv_obj_t * ui_Label45 = NULL;
lv_obj_t * ui_Button30 = NULL;
lv_obj_t * ui_Label48 = NULL;
lv_obj_t * ui_Button34 = NULL;
lv_obj_t * ui_Label49 = NULL;
lv_obj_t * ui_Button35 = NULL;
lv_obj_t * ui_Label50 = NULL;
lv_obj_t * ui_Container18 = NULL;
lv_obj_t * ui_Label57 = NULL;
lv_obj_t * ui_Button41 = NULL;
lv_obj_t * ui_Label51 = NULL;
lv_obj_t * ui_Button36 = NULL;
lv_obj_t * ui_Label53 = NULL;
lv_obj_t * ui_Button38 = NULL;
lv_obj_t * ui_Label54 = NULL;
lv_obj_t * ui_Button39 = NULL;
lv_obj_t * ui_Label55 = NULL;
lv_obj_t * ui_Container16 = NULL;
lv_obj_t * ui_Label59 = NULL;
lv_obj_t * ui_Label58 = NULL;
lv_obj_t * ui_Switch6 = NULL;
lv_obj_t * ui_Label60 = NULL;
lv_obj_t * ui_Switch8 = NULL;
lv_obj_t * ui_Container19 = NULL;
lv_obj_t * ui_Label56 = NULL;
lv_obj_t * ui_RPMlable = NULL;
lv_obj_t * ui_Label62 = NULL;
lv_obj_t * ui_Slider6 = NULL;
lv_obj_t * ui_Label63 = NULL;
// event funtions
void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Image15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Image16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Image17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Image18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_Image19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCREEN_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen4_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label27, 100);
    lv_obj_set_height(ui_Label27, 40);
    lv_obj_set_x(ui_Label27, 100);
    lv_obj_set_y(ui_Label27, 30);
    lv_label_set_text(ui_Label27, "风扇控制");
    lv_obj_set_style_text_font(ui_Label27, &ui_font_Font25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 80);
    lv_obj_set_height(ui_Container10, 500);
    lv_obj_set_x(ui_Container10, 0);
    lv_obj_set_y(ui_Container10, 30);
    lv_obj_remove_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button11 = lv_button_create(ui_Container10);
    lv_obj_set_width(ui_Button11, 80);
    lv_obj_set_height(ui_Button11, 100);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image15 = lv_image_create(ui_Button11);
    lv_image_set_src(ui_Image15, &ui_img_673166940);
    lv_obj_set_width(ui_Image15, 80);
    lv_obj_set_height(ui_Image15, 100);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image15, 80);

    ui_Button12 = lv_button_create(ui_Container10);
    lv_obj_set_width(ui_Button12, 80);
    lv_obj_set_height(ui_Button12, 100);
    lv_obj_set_x(ui_Button12, 0);
    lv_obj_set_y(ui_Button12, 100);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image16 = lv_image_create(ui_Button12);
    lv_image_set_src(ui_Image16, &ui_img_1663005091);
    lv_obj_set_width(ui_Image16, 80);
    lv_obj_set_height(ui_Image16, 100);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image16, 80);

    ui_Button13 = lv_button_create(ui_Container10);
    lv_obj_set_width(ui_Button13, 80);
    lv_obj_set_height(ui_Button13, 100);
    lv_obj_set_x(ui_Button13, 0);
    lv_obj_set_y(ui_Button13, 200);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0xBCD1D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image17 = lv_image_create(ui_Button13);
    lv_image_set_src(ui_Image17, &ui_img_399794486);
    lv_obj_set_width(ui_Image17, 80);
    lv_obj_set_height(ui_Image17, 100);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image17, 80);

    ui_Button14 = lv_button_create(ui_Container10);
    lv_obj_set_width(ui_Button14, 80);
    lv_obj_set_height(ui_Button14, 100);
    lv_obj_set_x(ui_Button14, 0);
    lv_obj_set_y(ui_Button14, 400);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image18 = lv_image_create(ui_Button14);
    lv_image_set_src(ui_Image18, &ui_img_1887403499);
    lv_obj_set_width(ui_Image18, 80);
    lv_obj_set_height(ui_Image18, 100);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image18, 80);

    ui_Button15 = lv_button_create(ui_Container10);
    lv_obj_set_width(ui_Button15, 80);
    lv_obj_set_height(ui_Button15, 100);
    lv_obj_set_x(ui_Button15, 0);
    lv_obj_set_y(ui_Button15, 300);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image19 = lv_image_create(ui_Button15);
    lv_image_set_src(ui_Image19, &ui_img_237420965);
    lv_obj_set_width(ui_Image19, 80);
    lv_obj_set_height(ui_Image19, 100);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image19, 80);

    ui_Container17 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container17);
    lv_obj_set_width(ui_Container17, 400);
    lv_obj_set_height(ui_Container17, 100);
    lv_obj_set_x(ui_Container17, 100);
    lv_obj_set_y(ui_Container17, 80);
    lv_obj_remove_flag(ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label52 = lv_label_create(ui_Container17);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label52, "风速档位");
    lv_obj_set_style_text_font(ui_Label52, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button37 = lv_button_create(ui_Container17);
    lv_obj_set_width(ui_Button37, 60);
    lv_obj_set_height(ui_Button37, 30);
    lv_obj_set_x(ui_Button37, 20);
    lv_obj_set_y(ui_Button37, 40);
    lv_obj_add_flag(ui_Button37, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button37, lv_color_hex(0xA5C6D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_Button37);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "底");
    lv_obj_set_style_text_font(ui_Label45, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button30 = lv_button_create(ui_Container17);
    lv_obj_set_width(ui_Button30, 60);
    lv_obj_set_height(ui_Button30, 30);
    lv_obj_set_x(ui_Button30, 100);
    lv_obj_set_y(ui_Button30, 40);
    lv_obj_add_flag(ui_Button30, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button30, lv_color_hex(0xA5C6D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label48 = lv_label_create(ui_Button30);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "中");
    lv_obj_set_style_text_font(ui_Label48, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button34 = lv_button_create(ui_Container17);
    lv_obj_set_width(ui_Button34, 60);
    lv_obj_set_height(ui_Button34, 30);
    lv_obj_set_x(ui_Button34, 180);
    lv_obj_set_y(ui_Button34, 40);
    lv_obj_add_flag(ui_Button34, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button34, lv_color_hex(0xA5C6D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_Button34);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "高");
    lv_obj_set_style_text_font(ui_Label49, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button35 = lv_button_create(ui_Container17);
    lv_obj_set_width(ui_Button35, 60);
    lv_obj_set_height(ui_Button35, 30);
    lv_obj_set_x(ui_Button35, 260);
    lv_obj_set_y(ui_Button35, 40);
    lv_obj_add_flag(ui_Button35, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button35, lv_color_hex(0xA5C6D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_Button35);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "强劲");
    lv_obj_set_style_text_font(ui_Label50, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container18 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container18);
    lv_obj_set_width(ui_Container18, 400);
    lv_obj_set_height(ui_Container18, 100);
    lv_obj_set_x(ui_Container18, 100);
    lv_obj_set_y(ui_Container18, 200);
    lv_obj_remove_flag(ui_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label57 = lv_label_create(ui_Container18);
    lv_obj_set_width(ui_Label57, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label57, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label57, "定时关闭");
    lv_obj_set_style_text_font(ui_Label57, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button41 = lv_button_create(ui_Container18);
    lv_obj_set_width(ui_Button41, 60);
    lv_obj_set_height(ui_Button41, 30);
    lv_obj_set_x(ui_Button41, 20);
    lv_obj_set_y(ui_Button41, 40);
    lv_obj_add_flag(ui_Button41, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button41, lv_color_hex(0xA5C6D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_Button41);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "30min");
    lv_obj_set_style_text_font(ui_Label51, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button36 = lv_button_create(ui_Container18);
    lv_obj_set_width(ui_Button36, 60);
    lv_obj_set_height(ui_Button36, 30);
    lv_obj_set_x(ui_Button36, 100);
    lv_obj_set_y(ui_Button36, 40);
    lv_obj_add_flag(ui_Button36, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button36, lv_color_hex(0xA5C6D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Button36);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "1h");
    lv_obj_set_style_text_font(ui_Label53, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button38 = lv_button_create(ui_Container18);
    lv_obj_set_width(ui_Button38, 60);
    lv_obj_set_height(ui_Button38, 30);
    lv_obj_set_x(ui_Button38, 180);
    lv_obj_set_y(ui_Button38, 40);
    lv_obj_add_flag(ui_Button38, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button38, lv_color_hex(0xA5C6D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_Button38);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "2h");
    lv_obj_set_style_text_font(ui_Label54, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button39 = lv_button_create(ui_Container18);
    lv_obj_set_width(ui_Button39, 60);
    lv_obj_set_height(ui_Button39, 30);
    lv_obj_set_x(ui_Button39, 260);
    lv_obj_set_y(ui_Button39, 40);
    lv_obj_add_flag(ui_Button39, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button39, lv_color_hex(0xA5C6D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55 = lv_label_create(ui_Button39);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "取消");
    lv_obj_set_style_text_font(ui_Label55, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container16 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_width(ui_Container16, 400);
    lv_obj_set_height(ui_Container16, 150);
    lv_obj_set_x(ui_Container16, 100);
    lv_obj_set_y(ui_Container16, 320);
    lv_obj_remove_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label59 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label59, "其他控制");
    lv_obj_set_style_text_font(ui_Label59, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label58 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label58, 20);
    lv_obj_set_y(ui_Label58, 50);
    lv_label_set_text(ui_Label58, "摇头模式");
    lv_obj_set_style_text_font(ui_Label58, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch6 = lv_switch_create(ui_Container16);
    lv_obj_set_width(ui_Switch6, 50);
    lv_obj_set_height(ui_Switch6, 25);
    lv_obj_set_x(ui_Switch6, 300);
    lv_obj_set_y(ui_Switch6, 50);

    ui_Label60 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60, 20);
    lv_obj_set_y(ui_Label60, 100);
    lv_label_set_text(ui_Label60, "夜间静音");
    lv_obj_set_style_text_font(ui_Label60, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch8 = lv_switch_create(ui_Container16);
    lv_obj_set_width(ui_Switch8, 50);
    lv_obj_set_height(ui_Switch8, 25);
    lv_obj_set_x(ui_Switch8, 300);
    lv_obj_set_y(ui_Switch8, 100);

    ui_Container19 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container19);
    lv_obj_set_width(ui_Container19, 500);
    lv_obj_set_height(ui_Container19, 500);
    lv_obj_set_x(ui_Container19, 510);
    lv_obj_set_y(ui_Container19, 80);
    lv_obj_remove_flag(ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label56 = lv_label_create(ui_Container19);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label56, 20);
    lv_obj_set_y(ui_Label56, 200);
    lv_label_set_text(ui_Label56, "风扇DEV-003·运行状态");
    lv_obj_set_style_text_font(ui_Label56, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMlable = lv_label_create(ui_Container19);
    lv_obj_set_width(ui_RPMlable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMlable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMlable, 0);
    lv_obj_set_y(ui_RPMlable, 14);
    lv_obj_set_align(ui_RPMlable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPMlable, "0");
    lv_obj_set_style_text_color(ui_RPMlable, lv_color_hex(0x1372E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPMlable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPMlable, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label62 = lv_label_create(ui_Container19);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label62, 20);
    lv_obj_set_y(ui_Label62, 300);
    lv_label_set_text(ui_Label62, "转速调节");
    lv_obj_set_style_text_font(ui_Label62, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider6 = lv_slider_create(ui_Container19);
    lv_slider_set_value(ui_Slider6, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider6) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_Slider6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider6, 150);
    lv_obj_set_height(ui_Slider6, 10);
    lv_obj_set_x(ui_Slider6, 300);
    lv_obj_set_y(ui_Slider6, 300);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider6, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider6,
                                                                                              lv_obj_get_style_pad_right(ui_Slider6, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label63 = lv_label_create(ui_Container19);
    lv_obj_set_width(ui_Label63, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label63, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label63, 60);
    lv_obj_set_y(ui_Label63, 20);
    lv_obj_set_align(ui_Label63, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label63, "RPM");
    lv_obj_set_style_text_font(ui_Label63, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image15, ui_event_Image15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image16, ui_event_Image16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image17, ui_event_Image17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image18, ui_event_Image18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image19, ui_event_Image19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Label27 = NULL;
    ui_Container10 = NULL;
    ui_Button11 = NULL;
    ui_Image15 = NULL;
    ui_Button12 = NULL;
    ui_Image16 = NULL;
    ui_Button13 = NULL;
    ui_Image17 = NULL;
    ui_Button14 = NULL;
    ui_Image18 = NULL;
    ui_Button15 = NULL;
    ui_Image19 = NULL;
    ui_Container17 = NULL;
    ui_Label52 = NULL;
    ui_Button37 = NULL;
    ui_Label45 = NULL;
    ui_Button30 = NULL;
    ui_Label48 = NULL;
    ui_Button34 = NULL;
    ui_Label49 = NULL;
    ui_Button35 = NULL;
    ui_Label50 = NULL;
    ui_Container18 = NULL;
    ui_Label57 = NULL;
    ui_Button41 = NULL;
    ui_Label51 = NULL;
    ui_Button36 = NULL;
    ui_Label53 = NULL;
    ui_Button38 = NULL;
    ui_Label54 = NULL;
    ui_Button39 = NULL;
    ui_Label55 = NULL;
    ui_Container16 = NULL;
    ui_Label59 = NULL;
    ui_Label58 = NULL;
    ui_Switch6 = NULL;
    ui_Label60 = NULL;
    ui_Switch8 = NULL;
    ui_Container19 = NULL;
    ui_Label56 = NULL;
    ui_RPMlable = NULL;
    ui_Label62 = NULL;
    ui_Slider6 = NULL;
    ui_Label63 = NULL;

}
